services:
  backend:
    build: ./backend 
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend 
    environment:
      - DATABASE_URL=${DB_URL}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: