services:
  
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    restart: unless-stopped

  backend:
    build: ./backend 
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend 
    environment:
      - DB_NAME=theseed
      - DB_USER=postgres
      - DB_PASSWORD=postgres2025
      - DB_HOST=db
      - DB_PORT=5432
      - DB_ENGINE=django.db.backends.postgresql
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=theseed
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres2025
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
